// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Character struct {
	ID         int32       `json:"id"`
	Name       string      `json:"name"`
	Status     string      `json:"status"`
	Species    string      `json:"species"`
	Type       string      `json:"type"`
	Gender     string      `json:"gender"`
	Image      string      `json:"image"`
	Url        string      `json:"url"`
	Created    time.Time   `json:"created"`
	OriginID   pgtype.Int4 `json:"origin_id"`
	LocationID pgtype.Int4 `json:"location_id"`
}
