// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error)
	GetMissingCharacterIDs(ctx context.Context, dollar_1 []int32) ([]int32, error)
}

var _ Querier = (*Queries)(nil)
